# Generated by Django 5.2.5 on 2025-08-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='about/')),
                ('intro', models.TextField()),
                ('experience', models.TextField()),
                ('goal', models.TextField()),
            ],
        ),
    ]
