# Generated by Django 5.2.5 on 2025-08-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactmessage_education_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='name',
        ),
    ]
