# Generated by Django 5.2.5 on 2025-08-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_navigationitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='link',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
    ]
