# Generated by Django 5.2.5 on 2025-08-31 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_navigationitem_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationitem',
            name='link',
        ),
    ]
