# Generated by Django 5.2.5 on 2025-08-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_navigationitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='link',
            field=models.CharField(default='http://example.com', max_length=100),
            preserve_default=False,
        ),
    ]
