# Generated by Django 5.2.5 on 2025-08-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_navigationitem_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='intro_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sociallink',
            old_name='name',
            new_name='platform',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='welcome_text',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='icon',
        ),
        migrations.AddField(
            model_name='banner',
            name='designation',
            field=models.CharField(default='Manager', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='resume_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
