# Generated by Django 5.2.5 on 2025-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_stat_rename_intro_text_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], default='facebook', max_length=50),
        ),
    ]
